Repository Team-Talking-Potatoes/WeGo_BE, pull requests merged in 2024-12, with the labels that each got.

#26 🚀 deployment: 개발 환경 ci & cd 적용
  .github/workflows/deploy-dev.yml
  Dockerfile
Labels: 🚀 deployment

#33 ✨ feature: 여행 모임 생성 기능 추가
  src/main/java/potatoes/server/config/SwaggerConfig.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/CreateTravelRequest.java
  src/main/java/potatoes/server/entity/Travel.java
  src/main/java/potatoes/server/entity/TravelImage.java
  src/main/java/potatoes/server/entity/TravelPlan.java
  src/main/java/potatoes/server/entity/TravelUser.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/GlobalExceptionHandler.java
  src/main/java/potatoes/server/error/exception/AlreadyJoinedGatheringException.java
  src/main/java/potatoes/server/error/exception/GatheringNotFoundException.java
  src/main/java/potatoes/server/error/exception/NotParticipatingGatheringException.java
  src/main/java/potatoes/server/error/exception/PastGatheringException.java
  src/main/java/potatoes/server/error/exception/UnauthorizedGatheringCancelException.java
  src/main/java/potatoes/server/error/exception/UserNotFoundException.java
  src/main/java/potatoes/server/error/exception/WrongValueInCreateTravel.java
  src/main/java/potatoes/server/repository/TravelPlanRepository.java
  src/main/java/potatoes/server/repository/TravelRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/utils/time/DateTimeUtils.java
  src/test/java/potatoes/server/controller/TravelControllerTest.java
Labels: ✨ feature

#39 🔨️ refactor: 예외와 밸리데이션 재설정
  src/main/java/potatoes/server/controller/MailController.java
  src/main/java/potatoes/server/controller/UserController.java
  src/main/java/potatoes/server/service/UserService.java
Labels: 🔨 refactor

#46 🔨️ refactor: jwt 토큰 기반 인가 쿠키 기능 추가
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/CookieNotFound.java
  src/main/java/potatoes/server/utils/annotation/AuthorizationArgumentResolver.java
Labels: 🔨 refactor

#43 ✨ feat: 여행 생성 기능 API스펙 변경사항 적용
  src/main/java/potatoes/server/dto/CreateTravelRequest.java
  src/main/java/potatoes/server/entity/Travel.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/utils/time/DateTimeUtils.java
  src/test/java/potatoes/server/controller/TravelControllerTest.java
Labels: ✨ feature

#48 ✨ feat: 내가 만든 여행 조회 API
  src/main/java/potatoes/server/config/SwaggerConfig.java
  src/main/java/potatoes/server/constant/GatheringType.java
  src/main/java/potatoes/server/constant/TravelStatus.java
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/CreateReviewRequest.java
  src/main/java/potatoes/server/dto/GetMyReviewResponse.java
  src/main/java/potatoes/server/dto/GetMyTravelResponse.java
  src/main/java/potatoes/server/dto/ReviewPageResponse.java
  src/main/java/potatoes/server/dto/TravelPageResponse.java
  src/main/java/potatoes/server/entity/Review.java
  src/main/java/potatoes/server/entity/ReviewImage.java
  src/main/java/potatoes/server/entity/Travel.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/TravelNotFound.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#50 ✨ feature : 북마크 등록 및 삭제 기능 추가
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/entity/Bookmark.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/BookmarkNotFound.java
  src/main/java/potatoes/server/repository/BookmarkRepository.java
  src/main/java/potatoes/server/service/TravelService.java
  src/test/java/potatoes/server/controller/TravelControllerTest.java
Labels: ✨ feature

#52 ✨ feature : 북마크 등록 여행 조회
  src/main/java/potatoes/server/config/SwaggerConfig.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/GetMyTravelResponse.java
  src/main/java/potatoes/server/dto/TravelPageResponse.java
  src/main/java/potatoes/server/repository/BookmarkRepository.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/utils/pagination/PagePolymorphic.java
Labels: 🔨 refactor, ✨ feature

#53 [feat] 여행 상세조회 기능 추가
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/ParticipantResponse.java
  src/main/java/potatoes/server/dto/TravelDetailResponse.java
  src/main/java/potatoes/server/dto/TravelPlanResponse.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/TravelNotFound.java
  src/main/java/potatoes/server/repository/TravelPlanRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#56 ✨ feature : 리뷰작성이 가능한 여행을 조회합니다.
  src/main/java/potatoes/server/constant/SortByType.java
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/GetDetailsReview.java
  src/main/java/potatoes/server/dto/GetReviewResponse.java
  src/main/java/potatoes/server/dto/PageResponse.java
  src/main/java/potatoes/server/entity/ReviewLike.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/ReviewLikeAlreadyExist.java
  src/main/java/potatoes/server/error/exception/ReviewLikeNotFound.java
  src/main/java/potatoes/server/error/exception/ReviewNotFound.java
  src/main/java/potatoes/server/repository/ReviewLikeRepository.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#60 Revert "✨ feature : 리뷰작성이 가능한 여행을 조회합니다."
  src/main/java/potatoes/server/constant/SortByType.java
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/GetDetailsReview.java
  src/main/java/potatoes/server/dto/GetReviewResponse.java
  src/main/java/potatoes/server/dto/TravelPageResponse.java
  src/main/java/potatoes/server/entity/ReviewLike.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/error/exception/ReviewLikeAlreadyExist.java
  src/main/java/potatoes/server/error/exception/ReviewLikeNotFound.java
  src/main/java/potatoes/server/error/exception/ReviewNotFound.java
  src/main/java/potatoes/server/repository/ReviewLikeRepository.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix

#59 ✨ feature : 메인화면에 사용될 API 기능 추가
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/controller/UserController.java
  src/main/java/potatoes/server/dto/PopularUserResponse.java
  src/main/java/potatoes/server/dto/SimpleReviewResponse.java
  src/main/java/potatoes/server/dto/SimpleTravelResponse.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/repository/TravelRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/service/UserService.java
Labels: ✨ feature

#57 ✨ feature : 여행 리스트 조회 API 추가
  src/main/java/potatoes/server/constant/TravelSortType.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/TravelListResponse.java
  src/main/java/potatoes/server/dto/TravelSummaryResponse.java
  src/main/java/potatoes/server/repository/TravelRepository.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#66 ✨ feat : 응답 데이터에 userId 추가
  src/main/java/potatoes/server/dto/PopularUserResponse.java
  src/main/java/potatoes/server/service/UserService.java
Labels: ✨ feature

#63 🔨️ refactor : 예외 선언과 사용방식 변경
  src/main/java/potatoes/server/error/GlobalExceptionHandler.java
  src/main/java/potatoes/server/error/exception/AlreadyExistsEmail.java
  src/main/java/potatoes/server/error/exception/BookmarkNotFound.java
  src/main/java/potatoes/server/error/exception/CookieNotFound.java
  src/main/java/potatoes/server/error/exception/DuplicationEmail.java
  src/main/java/potatoes/server/error/exception/InvalidFileFormat.java
  src/main/java/potatoes/server/error/exception/InvalidSignInInformation.java
  src/main/java/potatoes/server/error/exception/JwtAuthException.java
  src/main/java/potatoes/server/error/exception/MailSendFailed.java
  src/main/java/potatoes/server/error/exception/MailVerifyNumberExpired.java
  src/main/java/potatoes/server/error/exception/MailVerifyNumberNotValid.java
  src/main/java/potatoes/server/error/exception/PasswordMismatch.java
  src/main/java/potatoes/server/error/exception/ReviewLikeAlreadyExist.java
  src/main/java/potatoes/server/error/exception/ReviewLikeNotFound.java
  src/main/java/potatoes/server/error/exception/ReviewNotFound.java
  src/main/java/potatoes/server/error/exception/S3FileUploadFailed.java
  src/main/java/potatoes/server/error/exception/TravelNotFound.java
  src/main/java/potatoes/server/error/exception/Unauthorized.java
  src/main/java/potatoes/server/error/exception/UserNotFound.java
  src/main/java/potatoes/server/error/exception/WeGoException.java
  src/main/java/potatoes/server/error/exception/WrongValueInCreateTravel.java
  src/main/java/potatoes/server/service/AuthService.java
  src/main/java/potatoes/server/service/CustomMailSender.java
  src/main/java/potatoes/server/service/MailVerificationService.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/service/UserService.java
  src/main/java/potatoes/server/utils/annotation/AuthorizationArgumentResolver.java
  src/main/java/potatoes/server/utils/jwt/JwtTokenUtil.java
  src/main/java/potatoes/server/utils/s3/S3UtilsProvider.java
  src/test/java/potatoes/server/controller/UserControllerTest.java
Labels: 🔨 refactor

#71 ✨ feat : 로컬과 배포 프론트에 대한 CORS 허용 설정 추가
  src/main/java/potatoes/server/config/WebConfig.java
Labels: ✨ feature

#72 🐛 fix : CORS허용 OriginPattern 오타 수정
  src/main/java/potatoes/server/config/WebConfig.java
Labels: 🐛 fix

#73 🐛 fix : OriginPattern 수정
  src/main/java/potatoes/server/config/WebConfig.java
Labels: 🐛 fix

#69 🔨️ refactor : 유저 정보 조회API에서 userId를 반환하게 변경
  src/main/java/potatoes/server/dto/GetUserProfileResponse.java
  src/main/java/potatoes/server/service/UserService.java
Labels: 🔨 refactor

#75 🔨️ refactor : 토큰 samesite 해제
  src/main/java/potatoes/server/utils/crypto/CookieProvider.java
Labels: 📝 chore

#77 ✨ feat : api 공통 응답 포맷 추가
  src/main/java/potatoes/server/controller/AuthController.java
  src/main/java/potatoes/server/controller/MailController.java
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/controller/UserController.java
  src/main/java/potatoes/server/dto/CommonResponse.java
Labels: ✨ feature

#79 🔨️ refactor : 토큰 설정 변경
  src/main/java/potatoes/server/controller/AuthController.java
  src/main/java/potatoes/server/service/AuthService.java
  src/main/java/potatoes/server/utils/crypto/CookieProvider.java
Labels: 🔨 refactor

#83 🔨️refactor : 프론트 로컬환경에서 쿠키 도메인 설정
  src/main/java/potatoes/server/utils/crypto/CookieProvider.java
Labels: 🔨 refactor

#88 🔨️refactor : 쿠키와 cors설정 프론트 대응 및 요구사항 조정
  src/main/java/potatoes/server/config/WebConfig.java
  src/main/java/potatoes/server/utils/crypto/CookieProvider.java
Labels: 🔨 refactor

#93 🔨️refactor : cors설정 변경
  src/main/java/potatoes/server/config/WebConfig.java
Labels: 📝 chore

#84 ✨ feat : 관리자 여행취소, 동행 취소 등록 구현
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#95 🔨️refactor : 회원 탈퇴로직을 비밀번호 인증과 탈퇴 로직으로 분리
  src/main/java/potatoes/server/controller/UserController.java
  src/main/java/potatoes/server/dto/GetUserProfileResponse.java
  src/main/java/potatoes/server/dto/PasswordCertification.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/service/MailVerificationService.java
  src/main/java/potatoes/server/service/UserService.java
Labels: 🔨 refactor

#97 ✨ feat : 여행 리뷰에 여행장 태그 추가
  src/main/java/potatoes/server/dto/CreateReviewRequest.java
  src/main/java/potatoes/server/entity/Review.java
  src/main/java/potatoes/server/service/ReviewService.java
Labels: ✨ feature
