Repository Team-Talking-Potatoes/WeGo_BE, pull requests merged in 2025-01, with the labels that each got.

#105 📚 docs : 채팅기능 Swagger에 추가
  src/main/java/potatoes/server/config/SwaggerConfig.java
Labels: 📚 docs

#107 🐛 fix : 여행 생성 실패 에러 수정
  src/main/java/potatoes/server/entity/Chat.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix

#111 🔨️refactor : 비로그인 상황에서 여행 조회 관련 api 변경
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/TravelDetailResponse.java
  src/main/java/potatoes/server/dto/TravelSummaryResponse.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🔨 refactor

#115 ✨ feature : 채팅 리스트 정렬기능 추가
  src/main/java/potatoes/server/constant/ChatSortType.java
  src/main/java/potatoes/server/controller/ChatController.java
  src/main/java/potatoes/server/repository/ChatMessageUserRepository.java
  src/main/java/potatoes/server/repository/TravelUserRepository.java
  src/main/java/potatoes/server/service/ChatService.java
  src/main/java/potatoes/server/utils/time/DateTimeUtils.java
Labels: ✨ feature

#118 📝 chore : 프론트 엔드 테스트용 더미데이터 생성
  src/main/java/potatoes/server/config/DataLoader.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: 📝 chore

#120 📝 chore: 여행리스트 조회 응답 형태 변경
  src/main/java/potatoes/server/dto/ChatSummaryResponse.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: 📝 chore

#122 🔨️refactor : 비로그인 userId -1 분기처리 optional 로 진행
  src/main/java/potatoes/server/controller/AuthController.java
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/TravelSummaryResponse.java
  src/main/java/potatoes/server/repository/ReviewLikeRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
  src/main/java/potatoes/server/service/TravelService.java
  src/main/java/potatoes/server/utils/annotation/NonLoginAuthorizationArgumentResolver.java
Labels: 🔨 refactor

#126 🐛 fix : 채팅이 없을 때 발생하는 에러 수정
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#128 🐛 fix : 회원가입 밸리데이션 수정
  src/main/java/potatoes/server/dto/SignUpRequest.java
Labels: 🐛 fix

#130 ✨ feature : 리뷰 종합 비율 계산 api
  src/main/java/potatoes/server/controller/ReviewController.java
  src/main/java/potatoes/server/dto/TotalCountReviews.java
  src/main/java/potatoes/server/dto/TotalRatingResponse.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/service/ReviewService.java
Labels: ✨ feature

#134 🔨️ refactor : WebSocket 인증 쿠키를 받는 방법 변경
  src/main/java/potatoes/server/config/WebConfig.java
  src/main/java/potatoes/server/config/WssConfig.java
  src/main/java/potatoes/server/dto/MessageSubscribe.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/service/ChatService.java
  src/main/java/potatoes/server/utils/stomp/ChatEventHandler.java
  src/main/java/potatoes/server/utils/stomp/CustomHandshakeInterceptor.java
  src/main/java/potatoes/server/utils/stomp/StompUserPrincipal.java
  src/main/java/potatoes/server/utils/stomp/WebSocketEventListener.java
Labels: 🐛 fix, 🔨 refactor

#140 🐛 fix : 유저가 중복 참여되는 문제 해결
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#143 🐛 fix : 프런트 웹소켓 연결 실패 문제 해결
  src/main/java/potatoes/server/config/WssConfig.java
  src/main/java/potatoes/server/utils/stomp/ChatEventHandler.java
Labels: 🐛 fix

#146 🐛 fix : 이미지 빈값 반환 에러 수정
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#150 ✨ feature : 여행 조회, 리뷰리스트 추가반환
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/dto/GetMyReviewResponse.java
  src/main/java/potatoes/server/dto/GetReviewResponse.java
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/repository/TravelRepository.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix, ✨ feature

#151 🐛 fix : 여행 checked 엔드포인트 포매팅 깨져있는문제
  src/main/java/potatoes/server/controller/TravelController.java
Labels: 🐛 fix

#156 🔨️ refactor : 여행조회 범위 와 더미데이터 값 재수정
  src/main/java/potatoes/server/repository/TravelRepository.java
Labels: 🐛 fix

#157 🐛 fix : 채팅 이미지 관련 에러 수정
  src/main/java/potatoes/server/entity/ChatImage.java
  src/main/java/potatoes/server/entity/ChatMessage.java
  src/main/java/potatoes/server/repository/ChatImageRepository.java
  src/main/java/potatoes/server/repository/ChatMessageUserRepository.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#159 ✨ feature : STOMP 채팅방 목록 업데이트 토픽 추가
  src/main/java/potatoes/server/config/WssConfig.java
  src/main/java/potatoes/server/dto/AlarmSubscribe.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/service/ChatService.java
  src/main/java/potatoes/server/utils/stomp/ChatEventHandler.java
Labels: ✨ feature

#161 ✨ feature : 채팅방 나가기 기능 추가
  src/main/java/potatoes/server/controller/ChatController.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#163 ✨ feature : 여행 등록 상세 일정 선택사항으로 변경
  src/main/java/potatoes/server/dto/CreateTravelRequest.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#165 ✨ feature : 상세 일정 데이터 값 Valid 변경
  src/main/java/potatoes/server/dto/CreateTravelRequest.java
  src/main/java/potatoes/server/entity/TravelPlan.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: ✨ feature

#167 🐛 fix : 채팅방 업데이트 Topic publish 경로 수정
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#169 ✨ feature : 참여자 및 앨범 조회 API 응답 형태 변경
  src/main/java/potatoes/server/dto/ChatAlbumResponse.java
  src/main/java/potatoes/server/repository/ChatMessageRepository.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#171 ✨ feature : STOMP 채팅방 목록 업데이트 Publish 조건 추가
  src/main/java/potatoes/server/entity/Chat.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#173 🐛 fix : 채팅 참여알람 오류 수정
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#175 ✨ feature : STOMP 채팅방 목록 업데이트 토픽 메시지 형태 수정
  src/main/java/potatoes/server/dto/AlarmSubscribe.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#177 🔨️ refactor : 여행상세 북마크 여부 반환하게 변경
  src/main/java/potatoes/server/dto/TravelDetailResponse.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🔨 refactor, ✨ feature

#179 🐛 fix : 여행 조회 쿼리 조건 수정
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix

#184 [feat] 참여하지 않은 채팅방의 읽지 않은 메시지 숫자 고정
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#185 ✨ feature : 채팅방 목록 업데이트 Topic 알림 종류 추가
  src/main/java/potatoes/server/constant/AlarmStatus.java
  src/main/java/potatoes/server/dto/AlarmSubscribe.java
  src/main/java/potatoes/server/service/ChatService.java
Labels: ✨ feature

#190 🔨️ refactor : 인기여행 조회 api 스팩 변경
  src/main/java/potatoes/server/controller/TravelController.java
  src/main/java/potatoes/server/repository/TravelRepository.java
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🔨 refactor

#191 ✨ feature : NoResourceFoundException 예외처리 추가
  src/main/java/potatoes/server/error/GlobalExceptionHandler.java
Labels: ✨ feature

#193 🐛 fix : 여행 조회 에서 haxNext와 page가 예상과 다른문제
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix

#195 ✨ feature : STOMP 채팅방 목록 업데이트 Topic 메시지 전송 조건 변경
  src/main/java/potatoes/server/entity/Chat.java
  src/main/java/potatoes/server/error/ErrorCode.java
  src/main/java/potatoes/server/repository/ChatRepository.java
  src/main/java/potatoes/server/service/ChatService.java
  src/main/java/potatoes/server/utils/stomp/ChatEventHandler.java
  src/main/java/potatoes/server/utils/stomp/CustomHandshakeInterceptor.java
  src/main/java/potatoes/server/utils/stomp/WebSocketEventListener.java
Labels: ✨ feature

#197 🐛 fix : 인기 리뷰인 해시태그 전달
  src/main/java/potatoes/server/repository/ReviewRepository.java
  src/main/java/potatoes/server/service/UserService.java
Labels: ✨ feature

#199 🐛 fix : 여행 종료시각 수정
  src/main/java/potatoes/server/service/TravelService.java
Labels: 🐛 fix

#201 🐛 fix : blob 이 확장자 없애는 현상 대응
  src/main/java/potatoes/server/utils/s3/S3UtilsProvider.java
Labels: 🐛 fix

#203 🐛 fix : 채팅 리스트 조회 여행참가하지 않은 상태에서 조회 시도시 에러 발생 해결
  src/main/java/potatoes/server/service/ChatService.java
Labels: 🐛 fix

#205 🐛 fix : 북마크 된 여행만 조회되게 변경
  src/main/java/potatoes/server/repository/BookmarkRepository.java
Labels: 🐛 fix

#207 🐛 fix : 리뷰 삭제 조건 인수위치 변경
  src/main/java/potatoes/server/service/ReviewService.java
Labels: 🐛 fix

#211 ci cd 성능 측정용 워크플로 파일 변경
  .github/workflows/deploy-dev.yml
Labels: 🐎 performance, 🧪 test

#212 🐎 perf : jib도입으로 성능증가
  .github/workflows/deploy-dev.yml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 🐎 performance

#215 isBookMark -> bookmarkFlag
  src/main/java/potatoes/server/travel/dto/SimpleTravelResponse.java
Labels: 🔨 refactor

#216 [test] nickName -> nickname
  src/main/java/potatoes/server/user/dto/PopularUserResponse.java
Labels: 🚜 rename
